/**
 * 模板商城数据（单一真源，前端展示 + 创建网站选择 + Demo 预览共用）。
 *
 * 产品规则（AGENTS.md / P0-NAV-TEMPLATE-PUBLIC）：
 * - 每个模板必须有真实可渲染的不同页面结构（sections 顺序与组合不同），不是只换颜色；
 * - 模板预览无需登录；应用模板需要登录；
 * - preview 图片必须来自真实模板 demo 截图（tools/capture-template-previews.mjs），
 *   截图不存在时用 accent 渐变兜底。
 */
export const TEMPLATES = [
  {
    id: 'industrial-pro',
    slug: 'industrial-pro',
    name: 'Industrial Pro',
    industry: '机械 · B2B · 重工业',
    price: 299,
    is_free: false,
    status: 'published',
    market_tags: ['en-US', 'ru-RU', 'zh-CN'],
    style_tags: ['深蓝', '金属', '工业摄影', '大留白', '技术感'],
    accent: 'linear-gradient(135deg,#0f2a5f,#2563eb)',
    desc: '参数与规格优先的专业工业站：Hero → 信任 → 产品 → 应用 → 工程案例 → CTA。',
    popular: true,
    style_profile: {
      palette: ['#0f2a5f', '#2563eb', '#e2e8f0', '#0b1220'],
      typography: 'engineering / technical sans',
      mood: 'premium B2B industrial photography, generous negative space',
    },
    sections: [
      { id: 'hero', type: 'hero', label: 'Hero', props: {
        eyebrow: 'INDUSTRIAL EQUIPMENT MANUFACTURER',
        title: 'Engineered for Continuous Duty',
        description: 'Industrial-grade equipment built for demanding projects, certified for global markets.',
        cta: 'Request a Quote', align: 'left', background: 'dark', padding: 'comfortable',
      } },
      { id: 'trust', type: 'trust', label: '信任背书', props: { items: ['ISO 9001', 'CE', 'EAC', 'OEM / ODM'] } },
      { id: 'products', type: 'products', label: '核心产品', props: { eyebrow: 'PRODUCTS', title: 'Built to Specification' } },
      { id: 'applications', type: 'applications', label: '应用场景', props: { eyebrow: 'APPLICATIONS', title: 'Where Our Machines Run' } },
      { id: 'capability', type: 'capability', label: '制造能力', props: { eyebrow: 'CAPABILITY', title: 'From Casting to Commissioning' } },
      { id: 'cases', type: 'cases', label: '工程案例', props: { eyebrow: 'PROJECTS', title: 'Delivered Worldwide' } },
      { id: 'cta', type: 'cta', label: '询盘 CTA', props: { title: 'Get Engineering Answers in 24h', cta: 'Talk to an Engineer' } },
    ],
  },
  {
    id: 'supplier-minimal',
    slug: 'supplier-minimal',
    name: 'Supplier Minimal',
    industry: '通用外贸 · 综合供应',
    price: 0,
    is_free: true,
    status: 'published',
    market_tags: ['en-US', 'zh-CN'],
    style_tags: ['极简', '明亮', '快询盘', '短路径'],
    accent: 'linear-gradient(135deg,#4c1d95,#8b5cf6)',
    desc: '转化路径最短：Hero → 产品 → 信任 → CTA。适合多品类贸易商快速上线收询盘。',
    style_profile: {
      palette: ['#4c1d95', '#8b5cf6', '#f5f3ff', '#1e1b4b'],
      typography: 'clean geometric sans',
      mood: 'minimal international commerce, light backgrounds',
    },
    sections: [
      { id: 'hero', type: 'hero', label: 'Hero', props: {
        eyebrow: 'ONE-STOP SUPPLIER',
        title: 'Source Smarter. Ship Faster.',
        description: 'Consolidated sourcing, inspection and shipping for global buyers.',
        cta: 'Get Quotation', align: 'center', background: 'light', padding: 'compact',
      } },
      { id: 'products', type: 'products', label: '核心产品', props: { eyebrow: 'CATALOG', title: 'What We Supply' } },
      { id: 'trust', type: 'trust', label: '信任背书', props: { items: ['500+ SKUs', 'QC Inspection', 'FOB / DDP', 'Reply in 12h'] } },
      { id: 'cta', type: 'cta', label: '询盘 CTA', props: { title: 'Send Your RFQ Today', cta: 'Start Inquiry' } },
    ],
  },
  {
    id: 'russia-industrial',
    slug: 'russia-industrial',
    name: 'Russia Industrial',
    industry: '俄语区 · 工业设备',
    price: 399,
    is_free: false,
    status: 'published',
    market_tags: ['ru-RU', 'en-US'],
    style_tags: ['深色工业', '参数突出', '大数字', '高对比', '供货能力'],
    accent: 'linear-gradient(135deg,#111827,#dc2626)',
    desc: '按俄语区采购习惯：设备参数前置、大数字供货能力、交期与物流说明详尽。',
    style_profile: {
      palette: ['#111827', '#dc2626', '#f3f4f6', '#030712'],
      typography: 'bold condensed, large numerals',
      mood: 'high-contrast dark industrial, procurement-focused',
    },
    sections: [
      { id: 'hero', type: 'hero', label: 'Hero', props: {
        eyebrow: 'ПРОМЫШЛЕННОЕ ОБОРУДОВАНИЕ',
        title: 'Надёжные поставки\nдля крупных проектов',
        description: 'Технические характеристики, стабильные сроки поставки и поддержка на месте.',
        cta: 'Запросить расчёт', align: 'left', background: 'dark', padding: 'comfortable',
      } },
      { id: 'capability', type: 'capability', label: '供货能力', props: { eyebrow: 'ВОЗМОЖНОСТИ', title: 'Производство и логистика' } },
      { id: 'products', type: 'products', label: '产品参数', props: { eyebrow: 'ОБОРУДОВАНИЕ', title: 'Технические характеристики' } },
      { id: 'cases', type: 'cases', label: '项目案例', props: { eyebrow: 'ОБЪЕКТЫ', title: 'Реализованные проекты' } },
      { id: 'trust', type: 'trust', label: '信任背书', props: { items: ['EAC', 'ГОСТ', 'СНГ Доставка', 'Сервис в РФ'] } },
      { id: 'cta', type: 'cta', label: '询盘 CTA', props: { title: 'Коммерческое предложение за 24 часа', cta: 'Отправить заявку' } },
    ],
  },
  {
    id: 'food-export',
    slug: 'food-export',
    name: 'Food Export',
    industry: '食品 · 农产品出口',
    price: 259,
    is_free: false,
    status: 'published',
    market_tags: ['en-US', 'ru-RU', 'zh-CN'],
    style_tags: ['明亮', '自然光', '原料特写', '干净', '品质认证'],
    accent: 'linear-gradient(135deg,#166534,#84cc16)',
    desc: '食品出口质感：原料特写 → 认证与溯源 → 产品 → 产能 → CTA。',
    style_profile: {
      palette: ['#166534', '#84cc16', '#fefce8', '#14532d'],
      typography: 'warm humanist sans',
      mood: 'bright natural-light food photography, clean layout',
    },
    sections: [
      { id: 'hero', type: 'hero', label: 'Hero', props: {
        eyebrow: 'FOOD & AGRICULTURE EXPORT',
        title: 'From Origin to Your Table',
        description: 'Traceable sourcing, certified processing and reliable cold-chain export.',
        cta: 'Request Samples', align: 'center', background: 'light', padding: 'comfortable',
      } },
      { id: 'trust', type: 'trust', label: '认证与溯源', props: { items: ['HACCP', 'ISO 22000', 'FDA Registered', 'GlobalG.A.P.'] } },
      { id: 'products', type: 'products', label: '产品', props: { eyebrow: 'PRODUCTS', title: 'Seasonal & Stable Supply' } },
      { id: 'applications', type: 'applications', label: '应用场景', props: { eyebrow: 'CHANNELS', title: 'Retail · Food Service · Industry' } },
      { id: 'cta', type: 'cta', label: '询盘 CTA', props: { title: 'Request a Sample Pack', cta: 'Contact Export Team' } },
    ],
  },
  {
    id: 'electronics-global',
    slug: 'electronics-global',
    name: 'Electronics Global',
    industry: '消费电子 · 电子元器件',
    price: 349,
    is_free: false,
    status: 'published',
    market_tags: ['en-US', 'zh-CN'],
    style_tags: ['科技', '深色', '产品特写', '参数表', '国际感'],
    accent: 'linear-gradient(135deg,#082f49,#06b6d4)',
    desc: '科技产品站：深色 Hero → 参数矩阵 → 场景 → 认证 → CTA。',
    style_profile: {
      palette: ['#082f49', '#06b6d4', '#ecfeff', '#020617'],
      typography: 'neo-grotesque, tight tracking',
      mood: 'dark tech product close-ups, precise spec presentation',
    },
    sections: [
      { id: 'hero', type: 'hero', label: 'Hero', props: {
        eyebrow: 'CONSUMER ELECTRONICS ODM',
        title: 'Precision Electronics,\nGlobal Ready',
        description: 'ODM/OEM electronics with certified quality and agile engineering.',
        cta: 'Get the Spec Sheet', align: 'left', background: 'dark', padding: 'comfortable',
      } },
      { id: 'products', type: 'products', label: '产品矩阵', props: { eyebrow: 'PRODUCTS', title: 'Engineered Product Lines' } },
      { id: 'applications', type: 'applications', label: '应用场景', props: { eyebrow: 'USE CASES', title: 'Where They Deploy' } },
      { id: 'capability', type: 'capability', label: '研发与制造', props: { eyebrow: 'ENGINEERING', title: 'From Schematic to Mass Production' } },
      { id: 'trust', type: 'trust', label: '信任背书', props: { items: ['RoHS', 'FCC', 'CE', 'UL'] } },
      { id: 'cta', type: 'cta', label: '询盘 CTA', props: { title: 'Start Your ODM Project', cta: 'Book a Call' } },
    ],
  },
  {
    id: 'building-materials-pro',
    slug: 'building-materials-pro',
    name: 'Building Materials Pro',
    industry: '建材 · 装饰材料',
    price: 329,
    is_free: false,
    status: 'published',
    market_tags: ['en-US', 'ru-RU'],
    style_tags: ['暖灰', '工程感', '项目图', '耐久性', '批量供货'],
    accent: 'linear-gradient(135deg,#44403c,#d97706)',
    desc: '建材工程站：项目应用 → 产品体系 → 技术指标 → 大批量供货 → CTA。',
    style_profile: {
      palette: ['#44403c', '#d97706', '#fafaf9', '#1c1917'],
      typography: 'sturdy slab accents',
      mood: 'architectural project imagery, durability-first messaging',
    },
    sections: [
      { id: 'hero', type: 'hero', label: 'Hero', props: {
        eyebrow: 'BUILDING MATERIALS SUPPLIER',
        title: 'Materials That Outlast Projects',
        description: 'Certified building materials for developers and contractors, container-scale supply.',
        cta: 'Request Bulk Quote', align: 'left', background: 'light', padding: 'comfortable',
      } },
      { id: 'applications', type: 'applications', label: '工程应用', props: { eyebrow: 'PROJECTS', title: 'Applied on Real Sites' } },
      { id: 'products', type: 'products', label: '产品体系', props: { eyebrow: 'SYSTEMS', title: 'Full Material Systems' } },
      { id: 'capability', type: 'capability', label: '产能与交付', props: { eyebrow: 'SUPPLY', title: 'Container-Scale, On Schedule' } },
      { id: 'cases', type: 'cases', label: '案例', props: { eyebrow: 'REFERENCES', title: 'Delivered Projects' } },
      { id: 'cta', type: 'cta', label: '询盘 CTA', props: { title: 'Bulk Pricing in 24 Hours', cta: 'Send Project List' } },
    ],
  },
]

export const templateBySlug = (slug) => TEMPLATES.find((t) => t.slug === slug || t.id === slug)
